Error in start, check_environment was called before settings file was loaded, therefore no $basedir available.

diff --git a/functions/helper_functions b/functions/helper_functions
--- a/functions/helper_functions
+++ b/functions/helper_functions
@@ -405,25 +405,19 @@ check_environment() {
             exit 1
         fi
 
-        # Überprüfen, ob Bash installiert ist
-        if ! brew list bash &>/dev/null; then
-            echo "GNU Bash not found. Installing Bash via Homebrew..."
-            brew install bash
-            echo "Please restart the script using the newly installed Bash."
-            exit 1
+        # Überprüfen, ob GNU-Grep installiert ist
+        if ! brew list grep &>/dev/null; then
+            echo "GNU Grep not found. Installing grep via Homebrew..."
+            brew install grep
         fi
 
-        # Überprüfen, ob die benötigten Tools (grep, sed, awk) in GNU-Versionen installiert sind
-        tools=("grep" "sed" "awk")
-        for tool in "${tools[@]}"; do
-            if ! brew list gnu-"$tool" &>/dev/null; then
-                echo "Installing GNU $tool via Homebrew..."
-                brew install gnu-"$tool"
-            fi
-        done
+        # Überprüfen, ob GNU-Awk installiert ist
+        if ! brew list awk &>/dev/null; then
+            echo "GNU Awk not found. Installing awk via Homebrew..."
+            brew install awk
+        fi
 
         # Aliase für GNU-Tools setzen
-        export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
         export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
         export PATH="/usr/local/opt/gawk/libexec/gnubin:$PATH"
 
@@ -445,7 +439,7 @@ check_environment() {
         if [ ! -f "$midi_monitor_binary" ]; then
             echo "MIDI monitor binary not found. Compiling midi_monitor..."
             gcc -o "$midi_monitor_binary" "$midi_monitor_source" -framework CoreMIDI -framework CoreFoundation
-            if [ $? -ne 0 ]; then
+            if [ -f $midi_monitor_binary]; then
                 echo "Compilation of midi_monitor failed. Please check the source file."
                 exit 1
             fi
