Massive changes in code due to warnings of shellcheck tool. Mainly added quoting around variables and fixed other coding style issues.

diff --git a/check_scripts b/check_scripts
--- a/check_scripts
+++ b/check_scripts
@@ -1,13 +1,23 @@
 #!/bin/bash
-SHELLCHECK=$(which shellcheck)
+SHELLCHECK=$(command -v shellcheck)
 if [[ -n "$SHELLCHECK" && -x $SHELLCHECK ]]; then
   EXITCODE=0
-  for i in $(find ./ -type f | grep -v '\(/name$\)\|\(\.map\)\|\(\.txt$\)\|\(midi_monitor/\)\|\(\.git\)\|\(README\.MD\)\|\(/developer_communication/\)') ; do
-    if ! $SHELLCHECK -s bash "$i" ; then
+  for i in $(find ./ -type f | grep -v '\(/name$\)\|\(\.conf\)\|\(\.map\)\|\(\.txt$\)\|\(midi_monitor/\)\|\(\.git\)\|\(README\.MD\)\|\(/developer_communication/\)') ; do
+    # SC2154: Disalb checkinf for referencing unassigned variable.
+    # this is done because we do a lot of sourcing, variables are defined
+    # in scripts where they are not referenced and vice versa.
+    # SC1090: disable follow sourced files.
+    # SC2164: disable warning to catch failing 'cd' commands.
+    # SC2207: Suppress warning for not using read -a or mapfile to parse arrays.
+    # read -a and read -ar hadissues when strings started with space character.
+    if ! $SHELLCHECK -s bash -e SC2154,SC1090,SC2164,SC2207 "$i" ; then
       EXITCODE=1
       #break # end after first script with errors or warnings was found.
     fi
   done
+  if [[ $EXITCODE -eq 0 ]]; then
+    echo "No warnings."
+  fi
   exit $EXITCODE
 else
   echo "Please install shellcheeck."
