Added adjustment of value types from int to float. This implies waiting for rigctld to accept connections at startup. Value type adjustment is needed because some parameters like BAT sem to be int from --dump-caps output, but still yield decimal numbers when querying them.
Implemented anounce_rig_get_lp for all supported datatypes.

Put selecting and getting parameters on Knob 5 on layer 2 for XTouch Mini.

Rearranged order of switching numpad to numbers, evaluating RIG capabilities and starting MIDI.
We need to make shure that all capabilities are evaluated and adjusted before
sourcing in MIDI. MIDI will execute in a subshell and therefore will not get
updates afterwards.

diff --git a/start b/start
--- a/start
+++ b/start
@@ -49,8 +49,6 @@ else
   source "$config_file"
 fi
 
-# switch numpad to numbers
-setleds +num
 
 # Check if a rig model was set.
 if [[ $model -lt 1 ]]; then
@@ -64,11 +62,6 @@ get_rig_capabilities
 # Check environment (Operating system)
 check_environment
 
-# Use MIDI devices?
-if [[ $use_midi_device == "TRUE" ]]; then
-  source "$basedir/midi/reader" &
-fi
-
 # Process rigctld options
 declare -a rigctldoptions
 if [[ -v model ]]; then rigctldoptions+=(-m "$model"); fi
@@ -77,6 +70,37 @@ if [[ -v device_path ]]; then rigctldoptions+=(-r "$device_path"); fi
 if [[ -v serial_speed ]]; then rigctldoptions+=(-s "$serial_speed"); fi
 rigctld "${rigctldoptions[@]}" &
 unset rigctldoptions
+
+# Wait for rigctld to start up.
+maxretries=10
+numretries=0
+while true ; do
+  (( numretries++ ))
+  rigctl -m2 -r "$host:$port" "" >/dev/null 2>&1
+  if [[ $? -eq 2 ]]; then
+    if [[ $numretries -lt $maxretries ]]; then
+      sleep 1
+    else
+      echo "Cannot connect to rigctld after trying $numretries times. Exiting."
+      exit 1
+    fi
+  else
+    ###echo "Conected to rigctld after trying $numretries times."
+    break  
+  fi
+done
+unset numretries maxretries
+
+# Adjust rig capabilities, see doc for function.
+adjust_rig_capabilities
+
+# switch numpad to numbers
+setleds +num
+
+# Use MIDI devices?
+if [[ $use_midi_device == "TRUE" ]]; then
+  source "$basedir/midi/reader" &
+fi
 
 declare -a file_menu_entries
 declare -a file_menu_actions
